export const pedsDescriptions  = {
    "1": {"name": "Police Officer", "description": "A tough and authoritative police officer patrolling the streets of Vice City."},
    "2": {"name": "SWAT Officer", "description": "A heavily armed SWAT team member ready for intense combat situations."},
    "3": {"name": "FBI Agent", "description": "A federal agent investigating criminal activities in the city."},
    "4": {"name": "Army Soldier", "description": "A military personnel with strict discipline and combat training."},
    "5": {"name": "Paramedic", "description": "A medical professional dedicated to saving lives in emergencies."},
    "6": {"name": "Fireman", "description": "A brave firefighter responding to fires and rescue operations."},
    "7": {"name": "Golfer", "description": "A wealthy golf enthusiast enjoying the sunny courses of Vice City."},
    "9": {"name": "Random Lady", "description": "An ordinary woman going about her daily life in the city."},
    "10": {"name": "Bum", "description": "A homeless person struggling to survive on the streets."},
    "11": {"name": "Greaser", "description": "A 1950s-style greaser with a tough attitude and love for classic cars."},
    "12": {"name": "Random Guy", "description": "An average citizen living in Vice City."},
    "13": {"name": "Random Guy", "description": "A regular guy enjoying the vibrant city life."},
    "14": {"name": "Random Lady", "description": "A woman shopping or walking through the city streets."},
    "15": {"name": "Random Guy", "description": "A typical male resident of Vice City."},
    "16": {"name": "Random Guy", "description": "An ordinary man going about his business."},
    "17": {"name": "Beach Girl", "description": "A young woman enjoying the sun and sand at the beach."},
    "18": {"name": "Fat Beach Lady", "description": "A heavyset woman relaxing at the beach."},
    "19": {"name": "Beach Guy", "description": "A man in swimwear enjoying the coastal vibe."},
    "20": {"name": "Fat Beach Guy", "description": "A large man having fun at the beach."},
    "21": {"name": "Random Lady", "description": "A woman walking through urban areas."},
    "22": {"name": "Random Lady", "description": "A female resident going about her day."},
    "23": {"name": "Random Lady", "description": "A city woman with everyday concerns. Sells things."},
    "24": {"name": "Prostitute", "description": "A streetwalker looking for clients in shady areas."},
    "25": {"name": "Bum", "description": "A destitute person begging for change."},
    "26": {"name": "Bum", "description": "A homeless individual sleeping on sidewalks."},
    "27": {"name": "Random Guy", "description": "A man walking through the city streets."},
    "28": {"name": "Taxi Driver", "description": "A cabbie driving around looking for fares."},
    "29": {"name": "Haitian", "description": "A member of the Haitian gang in Vice City."},
    "30": {"name": "Criminal", "description": "A shady character involved in illegal activities."},
    "31": {"name": "Random Lady", "description": "A woman going about her daily routine."},
    "32": {"name": "Random Lady", "description": "A female pedestrian in urban areas."},
    "33": {"name": "Random Guy", "description": "A man walking through different neighborhoods."},
    "34": {"name": "Random Guy", "description": "An average male citizen of Vice City."},
    "35": {"name": "Random Lady", "description": "A woman shopping or chatting with friends."},
    "36": {"name": "Random Lady", "description": "A female resident enjoying city life."},
    "37": {"name": "Random Guy", "description": "A man hanging out in various locations."},
    "38": {"name": "Beach Lady", "description": "A woman in swimwear at the beach."},
    "39": {"name": "Beach Guy", "description": "A man enjoying the sunny beach atmosphere."},
    "40": {"name": "Beach Lady", "description": "A female beachgoer in summer attire."},
    "41": {"name": "Beach Guy", "description": "A male enjoying the coastal lifestyle."},
    "42": {"name": "Random Guy", "description": "An ordinary man in casual clothing."},
    "43": {"name": "Prostitute", "description": "A sex worker soliciting in red light districts."},
    "44": {"name": "Bum", "description": "A homeless person asking for spare change."},
    "45": {"name": "Bum", "description": "A street dweller with tattered clothes."},
    "46": {"name": "Random Guy", "description": "A man walking through the city."},
    "47": {"name": "Random Guy", "description": "A regular guy in casual attire."},
    "48": {"name": "Punk", "description": "A rebellious youth with punk fashion."},
    "49": {"name": "Prostitute", "description": "A streetwalker in revealing clothing."},
    "50": {"name": "Random Old Lady", "description": "An elderly woman walking slowly."},
    "51": {"name": "Punk", "description": "A punk rock enthusiast with wild style."},
    "52": {"name": "Random Guy", "description": "An average male pedestrian."},
    "53": {"name": "Random Lady", "description": "A woman in casual summer clothes."},
    "54": {"name": "Random Lady", "description": "A female resident running errands."},
    "55": {"name": "Random Guy", "description": "A man in everyday clothing."},
    "56": {"name": "Random Guy", "description": "An ordinary male citizen."},
    "57": {"name": "Beach Lady", "description": "A woman in bikini at the beach."},
    "58": {"name": "Beach Guy", "description": "A man in swim trunks enjoying the sun."},
    "59": {"name": "Beach Lady", "description": "A female beachgoer in summer wear."},
    "60": {"name": "Beach Guy", "description": "A male enjoying the beach scene."},
    "61": {"name": "Construction Worker", "description": "A hardhat-wearing laborer at work sites."},
    "62": {"name": "Golfer", "description": "A wealthy man playing golf in country clubs."},
    "63": {"name": "Golfer", "description": "A golf enthusiast in proper attire."},
    "64": {"name": "Golfer", "description": "A player enjoying the golf courses."},
    "65": {"name": "Beach Lady", "description": "A woman sunbathing at the beach."},
    "66": {"name": "Beach Guy", "description": "A man relaxing by the ocean."},
    "67": {"name": "Random Lady", "description": "A woman walking through town."},
    "68": {"name": "Random Guy", "description": "A man in casual urban clothing."},
    "69": {"name": "Random Guy", "description": "An average male pedestrian."},
    "70": {"name": "Prostitute", "description": "A street prostitute looking for clients."},
    "71": {"name": "Bum Lady", "description": "A homeless woman begging for money."},
    "72": {"name": "Random Guy", "description": "A man walking through neighborhoods."},
    "73": {"name": "Random Guy", "description": "An ordinary male resident."},
    "74": {"name": "Taxi Driver", "description": "A cab driver working long hours."},
    "75": {"name": "Random Woman", "description": "A female pedestrian in the city."},
    "76": {"name": "Skater Guy", "description": "A young skateboarder performing tricks."},
    "77": {"name": "Beach Lady", "description": "A woman enjoying the beach life."},
    "78": {"name": "Skater Guy", "description": "A skateboarding enthusiast at parks."},
    "79": {"name": "Young Woman Shopper", "description": "A fashionable young woman shopping."},
    "80": {"name": "Old Women Shopper", "description": "An elderly lady running errands."},
    "81": {"name": "Tourist", "description": "A visitor exploring Vice City attractions."},
    "82": {"name": "Tourist", "description": "A sightseer taking photos around town."},
    "83": {"name": "Cuban", "description": "A member of the Cuban gang in Vice City."},
    "84": {"name": "Cuban", "description": "A Cuban gangster involved in criminal activities."},
    "85": {"name": "Haitian", "description": "A Haitian gang member in the city."},
    "86": {"name": "Haitian", "description": "A member of the Haitian criminal organization."},
    "87": {"name": "Shark", "description": "A member of the Sharks street gang."},
    "88": {"name": "Shark", "description": "A gangster from the Sharks organization."},
    "89": {"name": "Diaz Guy", "description": "An enforcer working for Ricardo Diaz."},
    "90": {"name": "Diaz Guy", "description": "A thug in Diaz's criminal empire."},
    "91": {"name": "Security Guard", "description": "A guard protecting properties and businesses."},
    "92": {"name": "Security Guard", "description": "A uniformed security personnel on duty."},
    "93": {"name": "Biker", "description": "A motorcycle gang member with a tough attitude."},
    "94": {"name": "Biker", "description": "A leather-clad biker roaming the streets."},
    "95": {"name": "Vercetti Guy", "description": "A member of Tommy Vercetti's organization."},
    "96": {"name": "Vercetti Guy", "description": "An associate in Vercetti's criminal empire."},
    "97": {"name": "Undercover Cop", "description": "A plainclothes officer investigating crimes."},
    "98": {"name": "Undercover Cop", "description": "A detective working undercover operations."},
    "99": {"name": "Undercover Cop", "description": "A cop disguised as a civilian."},
    "100": {"name": "Undercover Cop", "description": "A police officer in plain clothes."},
    "101": {"name": "Undercover Cop", "description": "An undercover law enforcement agent."},
    "102": {"name": "Undercover Cop", "description": "A cop blending in with criminals."},
    "103": {"name": "Random Guy", "description": "An average male in the city."},
    "104": {"name": "Bodyguard", "description": "A tough personal protector for VIPs."},
    "105": {"name": "Prostitute", "description": "A streetwalker in revealing outfit."},
    "106": {"name": "Prostitute", "description": "A sex worker in red light districts."},
    "107": {"name": "Ricardo Diaz", "description": "A powerful and ruthless drug lord."},
    "108": {"name": "Love Fist Guy", "description": "A member of the rock band Love Fist."},
    "109": {"name": "Ken Rosenburg", "description": "A nervous, cocaine-addicted lawyer."},
    "110": {"name": "Candy Suxx", "description": "A famous porn star in Vice City."},
    "111": {"name": "Hilary", "description": "A nerdy car race organizer."},
    "112": {"name": "Love Fist", "description": "A flamboyant rock band member."},
    "113": {"name": "Phil", "description": "A paranoid record producer."},
    "114": {"name": "Rockstar Guy", "description": "A developer or tester character."},
    "115": {"name": "Sonny", "description": "The mafia boss of the Forelli family."},
    "116": {"name": "Lance", "description": "Tommy Vercetti's partner in crime."},
    "117": {"name": "Mercedes", "description": "Cortez's spoiled daughter."},
    "118": {"name": "Love Fist", "description": "Another member of the rock band."},
    "119": {"name": "Alex Scrub", "description": "A lazy and incompetent worker."},
    "120": {"name": "Officer Lance Vance", "description": "Lance Vance in police uniform."},
    "121": {"name": "Lance Vance", "description": "Tommy's ambitious criminal partner."},
    "122": {"name": "Cortez", "description": "An aging drug lord and arms dealer."},
    "123": {"name": "SWAT 2", "description": "Another SWAT team member variant."},
    "124": {"name": "Columbian", "description": "A member of the Columbian cartel."},
    "125": {"name": "Hilary", "description": "The race organizer in different clothes."},
    "126": {"name": "Mercedes", "description": "Cortez's daughter in another outfit."},
    "127": {"name": "Cam", "description": "A character from the film studio missions."},
    "128": {"name": "Cam", "description": "Another film studio-related character."},
    "129": {"name": "Phil", "description": "The record producer in different attire."},
    "130": {"name": "Phil", "description": "Phil in another clothing variant."},
    "131": {"name": "Bodyguard", "description": "A professional security personnel."},
    "132": {"name": "Pizza Worker", "description": "A delivery guy for Pizza Stack."},
    "133": {"name": "Taxi Driver", "description": "A cabbie in different uniform."},
    "134": {"name": "Taxi Driver", "description": "Another taxi driver variant."},
    "135": {"name": "Sailor", "description": "A navy sailor on leave in the city."},
    "136": {"name": "Sailor", "description": "Another sailor enjoying shore leave."},
    "137": {"name": "Sailor", "description": "A naval personnel in the city."},
    "138": {"name": "Chef", "description": "A restaurant cook in white uniform."},
    "139": {"name": "Criminal", "description": "A shady character involved in crimes."},
    "140": {"name": "French Guy", "description": "A pretentious French individual."},
    "141": {"name": "Worker", "description": "A blue-collar worker in the city."},
    "142": {"name": "Haitian", "description": "Another Haitian gang member."},
    "143": {"name": "Waitress", "description": "A restaurant server in uniform."},
    "144": {"name": "Forelli Member", "description": "A mafia member from the Forelli family."},
    "145": {"name": "Forelli Member", "description": "Another Forelli family gangster."},
    "146": {"name": "Forelli Member", "description": "A mobster working for Sonny."},
    "147": {"name": "Columbian", "description": "Another Columbian cartel member."},
    "148": {"name": "Random Guy", "description": "An average male pedestrian."},
    "149": {"name": "Beach Guy", "description": "A man enjoying the beach life."},
    "150": {"name": "Random Guy", "description": "An ordinary male resident."},
    "151": {"name": "Random Guy", "description": "A man walking through the city."},
    "152": {"name": "Random Guy", "description": "An average guy in casual clothes."},
    "153": {"name": "Drag Queen", "description": "A flamboyant drag performer."},
    "154": {"name": "Diaz Traitor", "description": "A traitor in Diaz's organization."},
    "155": {"name": "Random Guy", "description": "A male pedestrian in the city."},
    "156": {"name": "Random Guy", "description": "An ordinary man going about his day."},
    "157": {"name": "Stripper", "description": "An exotic dancer at the strip club."},
    "158": {"name": "Stripper", "description": "Another pole dancer at the club."},
    "159": {"name": "Stripper", "description": "A performer at the adult establishment."},
    "160": {"name": "Store Clerk", "description": "A convenience store cashier."},
    "161": {"name": "Tommy Vercetti", "description": "The main protagonist and mobster."},
    "162": {"name": "Tommy Vercetti (Business Suit)", "description": "Tommy in formal business attire."},
    "163": {"name": "Tommy Vercetti (SpandEx Overalls)", "description": "Tommy in racing outfit."},
    "164": {"name": "Tommy Vercetti (Golfer)", "description": "Tommy dressed for golfing."},
    "165": {"name": "Tommy Vercetti (Cuban)", "description": "Tommy disguised as Cuban."},
    "166": {"name": "Tommy Vercetti (Cop)", "description": "Tommy in police uniform."},
    "167": {"name": "Tommy Vercetti (Robbery Suit)", "description": "Tommy in robbery outfit."},
    "168": {"name": "Tommy Vercetti (T-Shirt and Jeans)", "description": "Tommy in casual wear."},
    "169": {"name": "Tommy Vercetti (Striped Suit)", "description": "Tommy in pinstripe suit."},
    "170": {"name": "Tommy Vercetti (Black Tracksuit)", "description": "Tommy in black athletic wear."},
    "171": {"name": "Tommy Vercetti (Red Tracksuit)", "description": "Tommy in red athletic wear."},
    "172": {"name": "Club Bouncer", "description": "A tough doorman at nightclubs."},
    "173": {"name": "Club Bouncer", "description": "Another muscular bouncer."},
    "174": {"name": "Stripclub Dancer", "description": "An exotic dancer at the club."},
    "175": {"name": "Random Guy", "description": "An average male in the city."},
    "176": {"name": "Stripclub Dancer", "description": "Another pole dancer performer."},
    "177": {"name": "Stripclub Dancer", "description": "An adult entertainer at the club."},
    "178": {"name": "Stripclub Dancer", "description": "A dancer in the strip club."},
    "179": {"name": "Gang Member", "description": "A generic street gang member."},
    "180": {"name": "Tommy Vercetti (Endgame T-Shirt)", "description": "Tommy in final mission outfit."},
    "181": {"name": "Forelli Thug", "description": "A Forelli family enforcer."},
    "182": {"name": "Forelli Thug", "description": "Another Forelli mobster."},
    "183": {"name": "Random Lady", "description": "A woman walking through the city."},
    "184": {"name": "Gang Member", "description": "A member of a street gang."},
    "185": {"name": "Party Waitress", "description": "A server at high-end parties."},
    "186": {"name": "Kent Paul", "description": "A British music manager with cockney accent."},
    "187": {"name": "Big Head Taxi Driver", "description": "A taxi driver with oversized head."}
}

export const zoneInfo = {
  "DTOWN": "Downtown Vice City - The bustling business district with skyscrapers and urban life",
  "BEACH3": "Ocean Beach - Popular beach area with hotels and the famous Ocean Drive",
  "BEACH2": "Washington Beach - Another beautiful beachfront with palm trees and resorts",
  "BEACH1": "Viceport Beach - Industrial beach area near the docks and shipping yards",
  "A_PORT": "Airport Area - Location of the Vice City International Airport",
  "STARI": "Starfish Island - Exclusive residential island for the wealthy elite",
  "PORNI": "Prawn Island - Business district with important buildings and corporations",
  "GOLFC": "Golf Club - The exclusive country club and golf course area",
  "JUNKY": "Junkyard - Industrial area with scrap yards and auto shops",
  "DOCKS": "Docks - The working port area with cargo ships and warehouses",
  "HAVANA": "Little Havana - Cuban neighborhood with vibrant culture and music",
  "HAITI": "Little Haiti - Haitian community area with distinct architecture"
};

export const weatherTypes = {
    "0": "Sunny",
    "1": "Cloudy",
    "2": "Rainy",
    "3": "Foggy",
    "4": "ExtraSunny",
    "5": "Hurricane",
    "6": "ExtraColours"
}

// Get day status depending in-game hour time.
export const helperFunctions = {
    getPartOfDay:function(hour){
      if (hour >= 5 && hour < 12) {
        return "morning";
      } else if (hour >= 12 && hour < 17) {
        return "afternoon";
      } else if (hour >= 17 && hour < 21) {
        return "evening";
      } else {
        return "night";
      }
    },
    genRandomID:function(){
      const chars = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      let hash = '';
      for (let i = 0; i < 8; i++)
        hash += chars.charAt(Math.floor(Math.random() * chars.length));
      return hash;
    }
}